#
# Configuration file for 'install-agentd.sh' and 'install-editor.sh' of
# the 'gfarm_zabbix' package.
#

# Directory where commands related to Gfarm (e.g. gfhost) exist.
GFARM_BINDIR=/usr/local/bin

# --prefix directory which was specified by config-gfarm
GFMD_CONFIG_PREFIX=/

# Configuration file for gfmd.
GFMD_CONF_FILE=$GFMD_CONFIG_PREFIX/etc/gfmd.conf

# PID file for the PostgreSQL daemon
POSTGRES_PID_FILE=$GFMD_CONFIG_PREFIX/var/gfarm-pgsql/postmaster.pid

# UNIX user privilege which is used by the PostgreSQL daemon
POSTGRES_USER=postgres

# Syslog file which logs messages reported by gfmd, gfsd and gfarm2fs.
GFARM_SYSLOG_FILE=/var/log/messages

# Installation prefix of Zabbix.
# A Zabbix agent executable is expected under
# ${ZABBIX_PREFIX}/sbin/.
ZABBIX_PREFIX=/usr

# Path to the Zabbix agent executable.
# (optional: Leave empty for auto-detection.)
ZABBIX_AGENT_BIN=

# Home directory of the 'zabbix' user.
ZABBIX_HOMEDIR=/var/lib/zabbix

# Directory where Zabbix external scripts reside.
ZABBIX_EXTSCRIPTDIR=/usr/lib/zabbix/externalscripts

# Zabbix Agent user configuration directory.
# (optional: Leave empty for auto-detection.)
ZABBIX_AGENTD_CONFSUBDIR=

# syslog facility to report errors by gfarm_zabbix.
ZABBIX_SYSLOG_FACILITY=local0
